# Generated by Django 3.0.2 on 2020-02-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subrubic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRubic',
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
                'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.rubric',),
        ),
    ]
