# Generated by Django 3.0.2 on 2020-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_additionalimage_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Пopядoк'),
        ),
    ]
